# -*- coding: utf-8 -*-
"""Taller2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bHAYNaICQISYuTeUL5MdaptipO_Df3XK
"""

#Taller 2 Python funciones

def tallerLogica():

  año= int(input("ingrese su año de nacimiento: "))
  edad= 2024 - año
                                                                              #ejercicio 1
  def edad1():
      if edad >= 18:
        return(f"{edad} Eres mayor de edad ante el estado colombiano")
      elif edad >=1 and edad <=18:
        return(f"{edad} usted es menor de edad")
      else:
        return(f"comado no valido ")


                                                                              #ejercicio 2
  def generacion():
    if año >=2013:
      return(f" Eres de la generacion Alpha")
    elif año <=2012 and año >=1997:
      return(f" Eres de la generacion Z")
    elif año <=1996 and año >=1981:
      return(f" Eres de la generacion Millennials")
    elif año <=1980 and año >=1965:
      return(f" Eres de la generacion X")
    elif año <=1964 and año >=1946:
      return(f" Eres de la generacion Baby Bommers")
    elif año <=1945 and año >=1926:
      return(f" Eres de la generacion Silenciosa")
    elif año <=1925 and año >=1915:
      return(f" Eres de la generacion Grandiosa")
    else:
      return(f" Eres de la generacion Interbellum")



                                                                             #ejercicio 3
  def division():
   if edad % 10 ==0:
     return ("tu edad es un numero redondo")
   else:
     return ("tu edad no es un redondo ")

  print(edad1())
  print(generacion())
  print(division())

tallerLogica()

def agenda():

  contactos={}

  def agregarContactos():
      Ncontacto= input("ingrese el contacto: ")
      telefono= input("ingrese su telefono: ")
      contactos[Ncontacto]={
              "telefono": telefono
      }
      print(f"{Ncontacto} contacto ya agragado ")

  def mostrarContacto():
        if contactos:
          print("estos son tus contactos ya agregados: ")
          for Ncontacto in contactos:
            print(f"(*1.{contactos})")
        else:
          print("no hay contactos")

  def modificarContacto():
        mContacto= input("elija un contacto: ")
        if mContacto in contactos:
          modificarTelefono= input("modifica el telefono")
          contactos[mContacto]["telefono"]= modificarTelefono
          print(f"modificaste {mContacto} y paso a {modificarTelefono}")
        else:
          print(f"la el contacto ingresado no existe")

  def buscarContactos():
      nombrebuscar= input("Que contacto desea buscar: ")
      if nombrebuscar in contactos:
        nombre= contactos[nombrebuscar]
        print(f"nombre: {nombrebuscar}")
        print(f"telefono:  {nombre['telefono']}")
      else:
        print("contacto no encontrado")



  while True:
      print("\n 1. agregar un contacto \n 2. lista de contactos \n 3. modificar un contacto \n 4. buscar un contacto  \n 5. fin ")
      op= input("ingrese el numero de la opcion que desea realizar: ")

      if op == "1":
        agregarContactos()
      elif op == "2":
        mostrarContacto()
      elif op == "3":
         modificarContacto()
      elif op == "4":
        buscarContactos()
      elif op == "5":
        print("fin")
        break
      else:
        print("opcion no valida")

agenda()

def lista():

  invitados= []

  def nombreInvitado():
    NI= input("ingrese los nombres de los invitados: ")
    invitados.append(NI)
    print(f" el nombre {NI} ha sido agregado")

  def eliminarInvitado():
    NI= input("ingrese el invitado que quiere eliminar: ")
    if NI in invitados:
      invitados.remove(NI)
      print(f"el mobre {NI} fue eliminado")
    else:
      print(f"el valor ingresado no existe, intentalo de nuevo")

  def editarInvitados():
    edInvitados = input("pronuncie el invitado: ")
    if edInvitados in invitados:
      editarInvitados= input("edite el invitado: ")
      indiceInvitado= invitados.index(edInvitados)
      invitados[indiceInvitado]= editarInvitados
      print(f"editaste {edInvitados} a {editarInvitados}")
    else:
      print(f"el invitado no existe ")

  def mostrarInvitado():
    if invitados:
      print("invitados")
      for NI in invitados:
        print(f"{NI}")
    else:
      print("no hay invitadosen el momento")




  while True:
    print("\n 1. agregar invitados \n 2. eliminar invitado \n 3. modificar invitado \n 4. ver invitado \n 5. salir ")
    op= input("ingrese el numero de la opcion que desea: ")

    if op == "1":
      nombreInvitado()
    elif op == "2":
      eliminarInvitado()
    elif op == "3":
      editarInvitados()
    elif op == "4":
      mostrarInvitado()
    elif op == "5":
      print("fin")
      break
    else:
      print("comando incorrecto")

lista()